FRC3620/FRC3620_2025_Akula_Mic

README.md
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commands/SetPivotPositionCommand.java
src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFEndEffectorMechanism.java

Need to figure out AFI roller (SparkMax.) We need to remake the endeffetor so that it is a sparkmax. (How to access SparkMax) -- Patrick, Atharv, Owen.

AFI Pivot Working

---

src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFEndEffectorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFShoulderMechanism.java

FIXED MOtor stuff

---

src/main/java/frc/robot/Robot.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/HealthSubsystem.java
src/main/java/org/usfirst/frc3620/Utilities.java

also some other minor fixes/enhancements

Detected unplugged swerve encoders

---

src/main/deploy/robot_parameters.json
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/RobotParameters.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedCommand.java
src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/HealthSubsystem.java

AFI subsystem encoder stuff learning opportunity.

Afi atharv 2 10

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commandfactories/AFISubsystemCommandFactory.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedContinuousCommand.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedUntilInCommand.java
src/main/java/frc/robot/subsystems/AFISubsystem.java

Created AFI set positions (need to be tuned.) 
Created ground pickup command
Created spit command.

AFI-Atharv-2/17 Ready to merge

---

src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFShoulderMechanism.java

ready to merge, speeding up esef has motion magic

motionmagic smoothed out elevator and sped

---

src/main/java/frc/robot/subsystems/AFISubsystem.java
vendordeps/yagsl-2025.7.0.json

Updated Yagsl to 25.7

---

README.md
src/main/deploy/robot_parameters.json
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commandfactories/AFISubsystemCommandFactory.java
src/main/java/frc/robot/commandfactories/ClimberCommandFactory.java
src/main/java/frc/robot/commandfactories/ESEFSubsystemCommandFactory.java
src/main/java/frc/robot/commandfactories/SwerveSubsystemCommandFactory.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedContinuousCommand.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedUntilInCommand.java
src/main/java/frc/robot/commands/TurnToAngleCommand.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilCoralGone.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilHasCoral.java
src/main/java/frc/robot/commands/esefcommands/SetESEFPositionCommand.java
src/main/java/frc/robot/commands/swervedrive/DriveToClosestStickCommand.java
src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFEndEffectorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFMech.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPosition.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFShoulderMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFSubsystem.java
src/main/java/frc/robot/subsystems/swervedrive/SwerveSubsystem.java
src/main/java/org/usfirst/frc3620/Utilities.java
src/test/java/MeasureClamp.java
src/test/java/MeasureClampGenerics.java

Neatened things up. should be ok, but should test on robot.

Esef interlocks refined

---

README.md
src/main/deploy/robot_parameters.json
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commandfactories/AFISubsystemCommandFactory.java
src/main/java/frc/robot/commandfactories/ClimberCommandFactory.java
src/main/java/frc/robot/commandfactories/ESEFSubsystemCommandFactory.java
src/main/java/frc/robot/commandfactories/SwerveSubsystemCommandFactory.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedContinuousCommand.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedUntilInCommand.java
src/main/java/frc/robot/commands/TurnToAngleCommand.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilCoralGone.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilHasCoral.java
src/main/java/frc/robot/commands/esefcommands/SetESEFPositionCommand.java
src/main/java/frc/robot/commands/swervedrive/DriveToClosestStickCommand.java
src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFEndEffectorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFMech.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPosition.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFShoulderMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFSubsystem.java
src/main/java/frc/robot/subsystems/swervedrive/SwerveSubsystem.java
src/main/java/org/usfirst/frc3620/Utilities.java
src/test/java/MeasureClamp.java
src/test/java/MeasureClampGenerics.java

Made climber motor in brake mode in the code.

Coded for Climer motor to be in brake mode. Not tested though

---

src/main/java/frc/robot/commandfactories/ESEFSubsystemCommandFactory.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilCoralGone.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPosition.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFShoulderMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFSubsystem.java

arm setpts good and fast and smooth

Finding coral placing positions

---

src/main/deploy/robot_parameters.json
src/main/java/frc/robot/RobotParameters.java
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java

Climber encoder

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commandfactories/ClimberCommandFactory.java
src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilHasAlgae.java
src/main/java/frc/robot/subsystems/AFISubsystem.java
src/main/java/frc/robot/subsystems/BlinkySubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFEndEffectorMechanism.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPosition.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFSubsystem.java

let's get these in right away.

Fixing algae operator

---

src/main/java/frc/robot/commandfactories/SwerveSubsystemCommandFactory.java
src/main/java/frc/robot/commands/swervedrive/DriveToClosestStickCommand.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java

DriveToClosestStickCommand was edited to use DriveToPoseCommand (YAGSL). The Blue Stick pose was also updated (using information from pathplanner)

Created "AutoAllign". It's working on JoeHann.

---

src/main/deploy/robot_parameters.json
src/main/java/org/usfirst/frc3620/RobotParametersBase.java
src/main/java/org/usfirst/frc3620/RobotParametersContainer.java
src/test/java/RobotParametersTest.json

We can preemptively add the serial number for our backup roboRIO to robotParameters, so if we swap it out, we get the right parameters.

We can have multiple serial numbers for the same config in RobotParameters.

---

src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/HealthSubsystem.java
src/main/java/org/usfirst/frc3620/motors/TalonFetcher.java

Tuned climber bound and added motor current output to SmartDashboard.

Climber set point and motor output

---

src/main/deploy/robot_parameters.json
src/main/deploy/swerve/Compbot/modules/backleft.json
src/main/deploy/swerve/Compbot/modules/backright.json
src/main/deploy/swerve/Compbot/modules/frontleft.json
src/main/deploy/swerve/Compbot/modules/frontright.json
src/main/java/frc/robot/subsystems/ClimberSubsystem.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPosition.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFPositionController.java

Fixed ESEF safety nets to match new funnels.
Fixed climber absolute encoder offset
Fixed swerve horacio bar.

Post-build changes absolute encoder fixes and safety nets.

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commands/swervedrive/DriveToClosestStickCommand.java
src/main/java/frc/robot/commands/swervedrive/DriveToPoseCommand.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java
src/main/java/frc/robot/subsystems/swervedrive/SwerveSubsystem.java

should have all autoalign code working, red side is good to the eyes of jared

Fix auto align command branch

---

src/main/deploy/pathplanner/autos/Processor STICKS LJ.auto
src/main/deploy/pathplanner/paths/Algae Pickup AB to Suck AB Algae.path
src/main/deploy/pathplanner/paths/Bottom Source to STICK I.path
src/main/deploy/pathplanner/paths/Bottom Source to STICK J.path
src/main/deploy/pathplanner/paths/Bottom Source to Stick K.path
src/main/deploy/pathplanner/paths/Center to STICK A.path
src/main/deploy/pathplanner/paths/PostBump to Wall Start.path
src/main/deploy/pathplanner/paths/STICK A to Algae Pickup AB.path
src/main/deploy/pathplanner/paths/STICK C to Wall Source.path
src/main/deploy/pathplanner/paths/STICK E to Wall Source.path
src/main/deploy/pathplanner/paths/STICK J to Bottom Source.path
src/main/deploy/pathplanner/paths/Source STICK L.path
src/main/deploy/pathplanner/paths/Stick F to Wall Source.path
src/main/deploy/pathplanner/paths/Stick I to Bottom Source.path
src/main/deploy/pathplanner/paths/Stick L to Bottom Source.path
src/main/deploy/pathplanner/paths/Suck Algae to Barge Score.path
src/main/deploy/pathplanner/paths/Wall Bump Angle.path
src/main/deploy/pathplanner/paths/Wall Bump Straight.path
src/main/deploy/pathplanner/paths/Wall Source to STICK E.path
src/main/deploy/pathplanner/paths/Wall Source to STICK F.path
src/main/deploy/pathplanner/paths/Wall to STICK C.path
src/main/deploy/pathplanner/settings.json

Woodhaven competition

---

src/main/java/frc/robot/subsystems/esefsubsystem/ESEFElevatorMechanism.java

Saw a lot of elevator home switch resets, wondering why...

Better logging on elevator reset

---

vendordeps/yagsl-2025.7.2.json

The new YAGSL 2025.7.2 works fine.

YAGSL 2025.7.2 update

---

src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/subsystems/BlinkySubsystem.java
src/main/java/frc/robot/subsystems/HealthSubsystem.java
src/main/java/org/usfirst/frc3620/CANDeviceFinder.java

Don't police light a non-competition robot unless swerve is broken.

Better police lights.

---

src/main/java/frc/robot/Robot.java
src/main/java/frc/robot/RobotContainer.java
src/main/java/frc/robot/commands/AFI/AFIRollerSetSpeedCommand.java
src/main/java/frc/robot/commands/esefcommands/SetEndEffectorSpeedCommand.java
src/main/java/frc/robot/commands/swervedrive/DriveToPoseCommand.java
src/main/java/frc/robot/subsystems/BlinkySubsystem.java

Fix up some logging in autoalign, add some command names, get rid of cruft.

Auto align logging

---

src/main/java/frc/robot/commandfactories/ESEFSubsystemCommandFactory.java
src/main/java/frc/robot/commands/esefcommands/SetESEFPositionPatientCommand.java
src/main/java/frc/robot/subsystems/esefsubsystem/ESEFSubsystem.java

Patient command is tested and working

---

src/main/java/frc/robot/commands/esefcommands/RunEndEffectorUntilHasAlgae.java
src/main/java/frc/robot/subsystems/VisionSubsystem.java

Red algae poses tuned
